### ISSUE TITLE
issue with dependency cppnanomsg 

### ISSUE THREAD

**Issue by sburke56** [sroycode/nanorpc#1]
A while ago you posted an issue to the cppnanomsg package that is a c++ bindings package for nanomsg.  It looks like that was around the time of creating this proof of concept.  Do you know how this was resolved since the line of code that you reference as being the problem is gone in the proof of concept.  

I'm looking at using this proof of concept so I'm trying to determine if I'm going to have issues going forward or not. 

> Hi:
> I am trying to make a proof-of-concept RPC with nanomsg and google protobuf. 
> The shutdown always gives EINVAL, what am I doing wrong ?

**Comment by sroycode** [comment]
I ended up switching back to zeromq ... in my view nanomsg is nowhere near production ready even now

**Comment by sburke56** [comment]
Ha do you remember why?

**Comment by sroycode** [comment]
The issue was with graceful closure , when I attempted to shutdown by interrupt the program would always crash ( forgot the exact error message) which was traced to a C nn_close() returning EINVAL . Since my project required graceful closure on interrupt this was a no-show.
( Just as an aside , there was a very similar bug in zeromq proxy )

**Comment by sburke56** [comment]
Thanks for the info.

**Comment by kuncao** [comment]
@sroycode @sburke56 
I reproduced the issue 
the detail is in 
https://github.com/nanomsg/cppnanomsg/issues/2
